version: "3.3"
services:
  back:
    container_name: back
    build: ../.
    restart: always
    env_file:
      - ../.env
    volumes:
      - static_dir:/app/static/
    depends_on:
      - database

  nginx:
    container_name: nginx
    image: nginx:1.23.3-alpine
    restart: always
    ports:
      - 80:80
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - static_dir:/etc/nginx/html/static/

    depends_on:
      - back

  database:
    container_name: database
    image: postgres:14.6-alpine
    restart: always
    env_file:
      - ../.env
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  static_dir:
  db-data:
