version: "3.3"
services:
  db:
    container_name: db
    image: postgres:14.6-alpine
    restart: always
    env_file:
      - ../.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  back:
    container_name: back
    build: ../.
    restart: always
    env_file:
      - ../.env
    volumes:
      - static_dir:/app/static/
    depends_on:
      - db
      - redis
    command: |
      bash -c "python3 manage.py makemigrations;
        python3 manage.py migrate;
        python3 manage.py loaddata fixtures/data.json;
        gunicorn it_bel_project.wsgi:application --bind 0:8000"
    environment:
      - DOCKER=True

  nginx:
    container_name: nginx
    image: nginx:1.23.3-alpine
    restart: always
    ports:
      - 80:80
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - static_dir:/etc/nginx/html/static/

    depends_on:
      - back
  redis:
    container_name: redis
    image: redis:7.0.11-alpine
    restart: always

volumes:
  static_dir:
  postgres_data:
